name: build image
on:
  push:
    branches:
      - master
    tags:
      - v*
permissions:
  packages: write
jobs:
  build:
    uses: csmith/github-workflows/.github/workflows/build-image.yml@master
    secrets: inherit
